Vagrant.configure ("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = nil
        ansible.raw_arguments = ["-i", "192.168.56.10"]
    end
end
