- name: Pull Jenkins agent image
  docker_image:
    name: jenkins/inbound-agent
    source: pull

- name: Run Jenkins agent container
  docker_container:
    name: jenkins-agent
    image: jenkins/inbound-agent
    state: started
    restart_policy: always
    env:
      JENKINS_URL: "http://{{ jenkins_master_ip }}:8080"
      JENKINS_AGENT_NAME: "agent1"
      JENKINS_SECRET: "{{ jenkins_agent_secret }}"
    networks:
      - name: "{{ docker_network_name }}"
        ipv4_address: "{{ jenkins_agent_ip }}"