Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.raw_arguments = ["--become"]  # Forza uso corretto
    ansible.verbose = "v"
  end
end
