---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Check if Podman is installed
  command: podman --version
  register: podman_check
  ignore_errors: yes

- name: Set container engine facts
  set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"
    podman_installed: "{{ podman_check.rc == 0 }}"

- name: Fail if no container engine is available
  fail:
    msg: "Neither Docker nor Podman is installed. Please install one of them."
  when: not docker_installed and not podman_installed

- name: Create directory for registry storage
  file:
    path: "{{ registry.storage_path | expanduser }}"
    state: directory
    mode: '0755'
  when: docker_installed

- name: Run local Docker registry
  community.docker.docker_container:
    name: "{{ registry.name }}"
    image: registry:2
    state: started
    restart_policy: always
    published_ports:
      - "0.0.0.0:{{ registry.port }}:5000"
    volumes:
      - "{{ registry.storage_path }}:/var/lib/registry"
    env:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
  when: docker_installed
  notify: restart registry

- name: Run local Podman registry
  containers.podman.podman_container:
    name: "{{ registry.name }}"
    image: registry:2
    state: started
    restart_policy: always
    publish:
      - "0.0.0.0:{{ registry.port }}:5000"
    volume:
      - "{{ registry.storage_path }}:/var/lib/registry"
    env:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
  when: podman_installed and not docker_installed
  notify: restart registry

- name: Wait for registry to be ready
  wait_for:
    host: 127.0.0.1
    port: "{{ registry.port }}"
    state: started
    delay: 5
    timeout: 60

- name: Login to Docker registry
  community.docker.docker_login:
    registry: "{{ registry.url }}"
    username: "{{ registry.username }}"
    password: "{{ registry.password }}"
  when: docker_installed

- name: Login to Podman registry
  containers.podman.podman_login:
    registry: "{{ registry.url }}"
    username: "{{ registry.username }}"
    password: "{{ registry.password }}"
  when: podman_installed and not docker_installed

- name: Verify registry login
  command: >
    {{ 'docker' if docker_installed else 'podman' }} login {{ registry.url }} --username {{ registry.username }} --password-stdin
  args:
    stdin: "{{ registry.password }}"
  register: login_check
  changed_when: false

- name: Show login status
  debug:
    msg: "✅ Successfully logged into {{ registry.url }}"
  when: login_check.rc == 0
