Vagrant.configure("2") do |config|
    config.vm.define "macchina1" do |macchina1|
        macchina1.vm.box = "ubuntu/bionic64"
        macchina1.vm.hostname = "macchina1"
        macchina1.vm.network "private_network", ip: "192.168.56.107"
        macchina1.vm.provision "shell", path: "provision.sh"
    end
    
    config.vm.define "macchina2" do |macchina2|
        macchina2.vm.box = "ubuntu/bionic64"
        macchina2.vm.hostname = "macchina2"
        macchina2.vm.network "private_network", ip: "192.168.56.108"
        macchina2.vm.provision "shell", path: "provision.sh"
    end
end
